force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Indicates the Home Country of the Customer</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field represent the External ID of the Contact inside to another System. It is used inside the ContactProductUtils class to allow the other System to retrieve the contacts.</description>
    <externalId>true</externalId>
    <label>Unique Identifier</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/ATM_Fee_in_other_Currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_Currencies__c</fullName>
    <label>ATM Fee in other Currencies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>This fields helps to identify the correct costs and fees by indicating the country of service.</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Home_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
        <label>France</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>Spain</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <label>United Kingdom</label>
    </customValue>
    <description>This Global Value Set is used to store the possible countries eligible to be the Home Country of the Customer</description>
    <masterLabel>Home Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestDataFactory.cls
public with sharing class TestDataFactory {

    public static Account TestAccount() {

        Account testAccount = new Account(
                                        Name = 'Test Account'
                                        );
        insert testAccount;
        return testAccount;

    }

    public static Contact TestFullContact(Id accountId) {

        Contact testContact = new Contact(
                                        FirstName = 'Test',
                                        LastName = 'Contact',
                                        AccountId = accountId,
                                        Product__c = 'Standard',
                                        Unique_Identifier__c = '12345',
                                        Home_Country__c = 'UK'
                                        );
        insert testContact;
        return testContact;

    }

    public static Contact TestIncompleteContact(Id accountId) {

        Contact testContact = new Contact(
                                        FirstName = 'Test',
                                        LastName = 'Contact',
                                        AccountId = accountId,
                                        Home_Country__c = 'UK'
                                        );
        insert testContact;
        return testContact;

    }



    public static Product2 TestProduct() {

        Product2 testProduct = new Product2(
                                        Name = 'Standard',
                                        ProductCode = 'STD',
                                        Description = 'Standard Product',
                                        IsActive = true,
                                        Home_Country__c = 'UK',
                                        Cost_per_Calendar_Month__c = 0,
                                        ATM_Fee_in_other_Currencies__c = 1.7,
                                        Card_Replacement_Cost__c = 6
                                        );
        insert testProduct;
        return testProduct;

    }

    public static Case TestCase(Id contactId) {

        Case testCase = new Case(
                                ContactId = contactId
                                );
        insert testCase;
        return testCase;

    }

    public static Case TestCaseNoContact() {

        Case testCase = new Case();
        insert testCase;
        return testCase;

    }

}