force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Indicates the Home Country of the Customer</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ATM_Fee_in_other_Currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_Currencies__c</fullName>
    <label>ATM Fee in other Currencies</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>This fields helps to identify the correct costs and fees by indicating the country of service.</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Home_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
        <label>Germany</label>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
        <label>France</label>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
        <label>Spain</label>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
        <label>Italy</label>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
        <label>United Kingdom</label>
    </customValue>
    <description>This Global Value Set is used to store the possible countries eligible to be the Home Country of the Customer</description>
    <masterLabel>Home Country</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomerRelatedProductController.cls
public with sharing class CustomerRelatedProductController {
    /*
    @AuraEnabled(cacheable=true)
    public static Product2 getCustomerProduct(Id contactId) {

        System.debug('Contact ID: ' + contactId);  
        
        try {
            //First Query to get the Product Name and Home Country of the Contact 
            Contact customerContact = [SELECT Id, Product__c,Home_Country__c
                                        FROM Contact
                                        WHERE Id =: contactId
                                        WITH SECURITY_ENFORCED
                                        LIMIT 1];
            System.debug('Customer Contact: ' + customerContact);

            //Second Query to get the Product details based on the Product Name and Home Country of the Contact
            Product2 customerProduct = [SELECT Id, Name, ProductCode, Description, Family, IsActive, Home_Country__c, Cost_per_Calendar_Month__c, ATM_Fee_in_other_Currencies__c, Card_Replacement_Cost__c
                                        FROM Product2 
                                        WHERE Name =: customerContact.Product__c
                                        AND Home_Country__c =: customerContact.Home_Country__c
                                        WITH SECURITY_ENFORCED
                                        LIMIT 1];
                                        
            System.debug('Customer Product: ' + customerProduct);
            return customerProduct;

        } catch (Exception excep) {
            throw new AuraHandledException(excep.getMessage());
        }
            
    }   
    */
    //Let's reuse the method from the Utils Class

    @AuraEnabled(cacheable=true)
    public static Product2 getCustomerProductComponent(Id contactId) {
        return ContactProductUtils.getCustomerProduct(contactId);
    }

    @AuraEnabled(cacheable=true)
    public static Contact getCustomerIdService(Id contactId) {
        return ContactProductUtils.getContactById(contactId);
    }
    
    //Rework dei metodi precedenti

    @AuraEnabled(cacheable=true)
    public static Product2 getCustomerProductComponent2(Id contactId) {
        return ContactProductUtils.getCustomerProductTry(ContactProductUtils.getContactById(contactId));
    }


    


}